// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
}
